CREATE GRAPH NIC (institution, relationship)
USE GRAPH NIC
BEGIN
CREATE LOADING JOB load_NIC FOR GRAPH NIC {
DEFINE FILENAME file1="/home/tigergraph/tigergraph/CSV_ATTRIBUTES_ACTIVE.CSV";
DEFINE FILENAME file2="/home/tigergraph/tigergraph/CSV_RELATIONSHIPS.CSV";
LOAD file1 TO VERTEX institution VALUES ($"#ID_RSSD", $"#ID_RSSD", $"D_DT_START", $"D_DT_END", $"BHC_IND", $"BROAD_REG_CD", $"CHTR_AUTH_CD", $"CHTR_TYPE_CD", $"FBO_4C9_IND", $"FHC_IND", $"FUNC_REG", $"INSUR_PRI_CD", $"MBR_FHLBS_IND", $"MBR_FRS_IND", $"SEC_RPTG_STATUS", $"EST_TYPE_CD", $"BANK_CNT", $"BNK_TYPE_ANALYS_CD", $" D_DT_EXIST_CMNC", $"D_DT_EXIST_TERM", $"FISC_YREND_MMDD", $"D_DT_INSUR", $"D_DT_OPEN", $"FNCL_SUB_HOLDER", $"FNCL_SUB_IND", $"IBA_GRNDFTHR_IND", $"IBF_IND", $"ID_RSSD_HD_OFF", $"MJR_OWN_MNRTY", $"NM_LGL", $"NM_SHORT", $"NM_SRCH_CD", $"ORG_TYPE_CD", $"REASON_TERM_CD", $"CNSRVTR_CD", $"ENTITY_TYPE", $"AUTH_REG_DIST_FRS", $"ACT_PRIM_CD", $"CITY", $"CNTRY_NM", $"ID_CUSIP", $"STATE_ABBR_NM", $"PLACE_CD", $"STATE_CD", $"STATE_HOME_CD", $"STREET_LINE1", $"STREET_LINE2", $"ZIP_CD", $"ID_THRIFT", $"ID_THRIFT_HC", $"DOMESTIC_IND", $"ID_ABA_PRIM", $"ID_FDIC_CERT", $"ID_NCUA", $"COUNTY_CD", $"DIST_FRS", $"ID_OCC", $"CNTRY_CD", $"DT_END", $"DT_EXIST_CMNC", $"DT_EXIST_TERM", $"DT_INSUR", $"DT_OPEN", $"DT_START", $"ID_TAX", $"PROV_REGION", $"URL", $"SLHC_IND", $"SLHC_TYPE_IND", $"PRIM_FED_REG", $"STATE_INC_CD", $"CNTRY_INC_CD", $"STATE_INC_ABBR_NM", $"CNTRY_INC_NM", $"ID_LEI", $"IHC_IND") USING header="true", separator=",";
LOAD file2 TO EDGE relationship VALUES ($0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) USING header="true", separator=",";
}
END
